---
# tasks file for roles/swarm

- name: install Docker SDK for python
  ansible.builtin.apt:
    pkg:
      - python3-docker
  become: true

- name: check/init swarm
  community.docker.docker_swarm:
    state: present
    advertise_addr: eth0
  register: swarm
  when: inventory_hostname in groups['swarm_manager']
  become: true

- name: join worker
  docker_swarm:
    state: join
    advertise_addr: eth0
    join_token: "{{ hostvars[groups['swarm_manager'][0]]['swarm']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: "{{ groups['swarm_manager'][0] }}"
  when: inventory_hostname in groups['swarm_worker']
  become: true
#  in case with more nodes
#  loop: "{{ groups['swarm_manager'] }}" iterate to the swarm_manager group to join all the workers to the swarm

- name: Correct /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "(.*?{{ groups['swarm_manager'][0] }})"
    line: \g<1> auth.vcc.local
    backrefs: true
  become: true